package com.backend.designpatterns.creational.factory.dagger;

/**
 * GOOGLE-STYLE DEMO
 * 
 * Note: DaggerNotificationComponent is GENERATED by Dagger's annotation processor.
 * You must run 'mvn compile' for this class to be found.
 */
public class DaggerDemo {

    public static void main(String[] args) {
        System.out.println("--- Google-Style Dagger 2 DI Demo ---");

        // 1. BOOTSTRAP: Initialize the Dagger graph
        // This is equivalent to Spring's ApplicationContext but it's generated at compile-time.
        NotificationComponent component = DaggerNotificationComponent.create();

        // 2. REQUEST SERVICE: Get a fully-formed UserService
        // Notice we didn't use 'new UserService(new EmailNotification())'.
        // Dagger handled the 'New' and the 'Injection' for us!
        UserService service = component.getUserService();

        // 3. USE SERVICE
        service.registerUser("picon_engineer");
    }
}
