name: compliance
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
        continue-on-error: false
      - name: license check (reporting-service)
        run: mvn -q -f reporting-service/pom.xml org.codehaus.mojo:license-maven-plugin:2.0.0:download-licenses

