spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/productivity
          jwk-set-uri: http://localhost:8089/realms/productivity/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: INFO

