apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: productivity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault
  namespace: productivity
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: productivity
spec:
  serviceName: vault
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:1.15
        args:
        - "server"
        env:
        - name: VAULT_LOCAL_CONFIG
          value: |
            ui = true
            listener "tcp" { address = "0.0.0.0:8200" tls_disable = 1 }
            storage "raft" { path = "/vault/data" retry_join = [{ leader_api_addr = "http://vault-0.vault:8200" }, { leader_api_addr = "http://vault-1.vault:8200" }] }
            api_addr = "http://$(POD_NAME).vault:8200"
            cluster_addr = "http://$(POD_NAME).vault:8201"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8200
          name: http
        volumeMounts:
        - name: data
          mountPath: /vault/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: productivity
spec:
  clusterIP: None
  selector:
    app: vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200

