package com.backend.generics;

import java.lang.reflect.Method;

/**
 * Step 03: Bridge Methods (The 'Invisible' Physics)
 * 
 * L7 Principles:
 * 1. Type Erasure: Generics only exist at compile-time. At runtime, they are Object.
 * 2. Bridge Methods: Synthesized methods created by the compiler to support covariance in generic types.
 * 3. Inheritance: What happens when a subclass provides a specific type for a generic parameter.
 */
public class Step03_BridgeMethods {

    public interface Processor<T> {
        void process(T data);
    }

    public static class StringProcessor implements Processor<String> {
        @Override
        public void process(String data) {
            System.out.println("Processing String: " + data);
        }
    }

    public static void main(String[] args) {
        System.out.println("=== Step 03: Bridge Methods (Bytecode Mechanics) ===");

        Class<?> clazz = StringProcessor.class;
        System.out.println("Methods in StringProcessor:");

        // L7 Mastery: Reflecting on the generated bytecode
        for (Method method : clazz.getDeclaredMethods()) {
            System.out.println(" - Name: " + method.getName() + " | Bridge: " + method.isBridge());
        }

        System.out.println("\nL5 Insight: The compiler creates a 'process(Object)' bridge method to satisfy the interface contract.");
        System.out.println("L7 Tip: Knowing about bridge methods is critical for debugging reflection-heavy frameworks.");
    }
}
