image:
  repository: gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

probe:
  path: /actuator/health
